# Generated by Django 4.1.6 on 2023-02-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
